rails_root = Pathname.new(File.dirname(__FILE__)).join("..")

gem "rack", "~> 1.0.0"
gem "rack-test", "~> 0.5.0"
gem "activesupport", "3.0.pre", :vendored_at => rails_root.join("activesupport")
gem "activemodel", "3.0.pre", :vendored_at => rails_root.join("activemodel")

only :test do
  gem "mocha"
  gem "sqlite3-ruby"
  gem "RedCloth"
  gem "memcache", "1.7.5", :vendored_at => rails_root.join("activesupport/lib/active_support/vendor/memcache-client-1.7.5")
end

disable_system_gems
