source "http://rubygems.org"

gemspec

gem 'rails', path: "/Users/drogus/code/rails/rails"#github: 'rails/rails'
gem 'active_record_deprecated_finders', github: 'rails/active_record_deprecated_finders'

gem 'sqlite3'
gem 'debugger'
